name: fyp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
